services:
  web:
    build: .
    command: bash -c "
        export REDIS_URL=redis://redis:6379/1 &&
        export SECRET_KEY_BASE=$(bin/rails secret) &&
        rm -f tmp/pids/server.pid &&
        bundle exec rake assets:precompile &&
        bundle exec rails db:migrate &&
        bundle exec rails server -b 0.0.0.0 -p 3000"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: production
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - redis

  worker:
    build: .
    command: bash -c "
        export REDIS_URL=redis://redis:6379/1 &&
        export SECRET_KEY_BASE=$(bin/rails secret) &&
        rm -f tmp/pids/server.pid &&
        bundle exec rails db:migrate &&
        bundle exec sidekiq"
    volumes:
      - .:/app
    environment:
      RAILS_ENV: production
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - redis

  redis:
    image: redis:6.2.5
    ports:
      - "6379:6379"

volumes:
  db-data:
