services:
  web:
    build: .
    entrypoint: ["./entrypoint.sh"]
    volumes:
      - .:/app
      - ./storage:/app/storage
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - redis

  worker:
    build: .
    command: ["bundle", "exec", "sidekiq"]
    entrypoint: ["./sidekiq-entrypoint.sh"]
    volumes:
      - .:/app
      - ./storage:/app/storage
    environment:
      RAILS_ENV: development
    depends_on:
      - redis

  redis:
    image: redis:6.2.5
    ports:
      - "6379:6379"

volumes:
  db-data: