services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0 -p 3000"
    entrypoint: ["./entrypoint.sh"]
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: production
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - redis

  worker:
    build: .
    command: bundle exec sidekiq
    entrypoint: ["./sidekiq-entrypoint.sh"]
    volumes:
      - .:/app
    environment:
      RAILS_ENV: production
    depends_on:
      - redis

  redis:
    image: redis:6.2.5
    ports:
      - "6379:6379"

volumes:
  db-data:
